site_name: Graphcore Research

nav:
  - Blog: index.md
  - "Our Papers": publications.md
  - "About Us": about.md

docs_dir: pages

theme:
  name: material
  custom_dir: templates
  logo: img/gc-symbol-white.png
  favicon: img/favicon.ico
  features:
    - content.code.copy

hooks:
  - hooks/merge_potm.py
  - hooks/notebook_to_markdown.py
  - hooks/render_page_templates.py

plugins:
  - blog:
      blog_dir: "."
      post_excerpt: required
      categories_allowed:
        - Articles
        - "Papers of the Month"
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra_css:
  - custom.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
