site_name: Graphcore Research

nav:
  - Blog: index.md
  - About: about.md
  - "Our Papers": publications.md

docs_dir: pages

theme:
  name: material
  custom_dir: templates
  logo: img/gc-symbol-white.png
  favicon: img/favicon.ico
  features:
    - content.code.copy

hooks:
  - hooks/render_page_templates.py
  - hooks/notebook_to_markdown.py

plugins:
  - blog: {blog_dir: "."}
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra_css:
  - custom.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
