site_name: Graphcore Research
copyright: Graphcore Research
site_url: https://graphcore-research.github.io

nav:
  - Blog: index.md
  - "↳ Articles": /category/articles
  - "↳ Papers of the Month": /category/papers-of-the-month
  - "Our Papers": publications.md
  - "About Us": about.md

docs_dir: pages

theme:
  name: material
  custom_dir: assets
  logo: img/gc-symbol-white.png
  favicon: img/favicon.ico
  features:
    - content.code.copy

hooks:
  - hooks/filter_only.py
  # content generation
  - hooks/render_notebook.py
  - hooks/render_page_template.py
  - hooks/render_potm.py
  - hooks/generate_author_pages.py
  - hooks/generate_redirects.py
  # other
  - hooks/see_also.py

plugins:
  - blog:
      blog_dir: "."
      post_excerpt: required
      categories_allowed:
        - Articles
        - "Papers of the Month"
      authors_profiles: true
      archive: false
  - search
  - social:
      cards_layout: default
      cards_layout_options:
        background_color: "#ff6d81"
        font_family: "Manrope"  # seems close to Graphik; must be a Google Font
  - tags

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - toc:
      toc_depth: "2-2"

extra_css:
  - custom.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - hiring_banner.js

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/GCResearchTeam
    - icon: fontawesome/brands/github
      link: https://github.com/graphcore-research
    - icon: fontawesome/solid/envelope
      link: https://www.graphcore.ai/graphcore-research-newsletter-1
    - icon: fontawesome/solid/book
      link: /publications
  analytics:
    provider: google
    property: G-QCZ6T9KWHQ
  consent:
    actions: [accept, reject, manage]
    description: >-
      This website stores a cookie on your computer to enable google analytics by default.
      If you decline this information will not be stored. All data is anonymized and will not
      be shared.
