[project]
name = "graphcore-research-blog"
version = "0.0"
requires-python = ">=3.10"
dependencies = [
    "nbconvert",
    "mkdocs",
    "mkdocs-material[imaging]",
]

[tool.setuptools]
packages = []
